/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import Commands.CommandMain;
import Commands.Tipos.Tipo;
import java.awt.Point;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author eidur
 */
public class pantallaPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form pantallaPrincipal
     */
    public boolean iniciada;
    public Cliente refCliente;
    public String nombreTurno = "";
    public int indexFi = 0;
    public Juego juego;
    private static pantallaPrincipal pantalla; 
    private pantallaPrincipal() {
        
        initComponents();
        this.juego = Juego.getIntance();
        this.jScrollPane2.getViewport().setOpaque(false);
        this.jScrollPane1.getViewport().setOpaque(false);
        //javax.swing.JLabel temp;
        /*
        for(int i =0; i<20;i++){
            for(int j =0; j<30;j++){
                temp = new javax.swing.JLabel("",javax.swing.SwingConstants.CENTER);
                temp.setPreferredSize(new java.awt.Dimension(20, 20));
                temp.setAlignmentY(0.0F);
                temp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
                temp.setOpaque(true);
                temp.setForeground(new java.awt.Color(255, 255, 255));
//              temp.setBackground(new java.awt.Color(114, 47, 55));
                int color = (new Random()).nextInt(3);
                switch(color){
                    case 0:
                        temp.setBackground(new java.awt.Color(6, 112, 187));
                        break;
                    case 1:
                        temp.setBackground(new java.awt.Color(197, 81, 40));
                        break;
                    case 2:
                        temp.setBackground(new java.awt.Color(64, 64, 64));
                        break;
                }
                this.juego.addPoblacion(temp, 5, i, j);
                matrizPanel.add(temp);
//                System.out.println("["+i+"]"+"["+j+"]");
            }
        }*/
    }
    
    public static synchronized pantallaPrincipal getIntance() {           
        if (pantalla == null) {               
            pantalla = new pantallaPrincipal();   
        }
        return pantalla;   
    } 
    
    
    public void setRefCliente(Cliente refCliente) {
        this.refCliente = refCliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        resultPanel = new javax.swing.JPanel();
        resultadoTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AtkResulttx = new javax.swing.JTextArea();
        luchadoresPanel = new javax.swing.JPanel();
        imageluchador1 = new javax.swing.JLabel();
        imageluchador3 = new javax.swing.JLabel();
        imageluchador2 = new javax.swing.JLabel();
        luchador2Panel1 = new javax.swing.JPanel();
        porcentajeluchador3 = new javax.swing.JLabel();
        nombre3 = new javax.swing.JLabel();
        tipo3 = new javax.swing.JLabel();
        poder1Title2 = new javax.swing.JLabel();
        poder3 = new javax.swing.JLabel();
        resistencia1Title2 = new javax.swing.JLabel();
        resistencia3 = new javax.swing.JLabel();
        sanidad1Title2 = new javax.swing.JLabel();
        sanidad3 = new javax.swing.JLabel();
        luchador2Panel = new javax.swing.JPanel();
        porcentajeluchador2 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JLabel();
        tipo2 = new javax.swing.JLabel();
        poder1Title1 = new javax.swing.JLabel();
        poder2 = new javax.swing.JLabel();
        resistencia1Title1 = new javax.swing.JLabel();
        resistencia2 = new javax.swing.JLabel();
        sanidad1Title1 = new javax.swing.JLabel();
        sanidad2 = new javax.swing.JLabel();
        luchador1Panel = new javax.swing.JPanel();
        porcentajeluchador1 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        tipo1 = new javax.swing.JLabel();
        poder1Title = new javax.swing.JLabel();
        poder1 = new javax.swing.JLabel();
        resistencia1Title = new javax.swing.JLabel();
        resistencia1 = new javax.swing.JLabel();
        sanidad1Title = new javax.swing.JLabel();
        sanidad1 = new javax.swing.JLabel();
        bitacoraPanel = new javax.swing.JPanel();
        bitacoraTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bitacoraTx = new javax.swing.JTextArea();
        cmdPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        consolaTx = new javax.swing.JTextArea();
        inputTf = new javax.swing.JTextField();
        tableroPanel = new javax.swing.JPanel();
        matrizPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        proporcion3 = new javax.swing.JLabel();
        nombrePorcentaje3 = new javax.swing.JLabel();
        nombreP3 = new javax.swing.JLabel();
        proporcion2 = new javax.swing.JLabel();
        nombrePorcentaje2 = new javax.swing.JLabel();
        nombreP2 = new javax.swing.JLabel();
        nombrePorcentaje1 = new javax.swing.JLabel();
        nombreP1 = new javax.swing.JLabel();
        proporcion1 = new javax.swing.JLabel();
        oceanoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultPanel.setBackground(new java.awt.Color(0, 153, 204));
        resultPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        resultPanel.setFocusable(false);
        resultPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultadoTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        resultadoTitle.setForeground(new java.awt.Color(240, 240, 240));
        resultadoTitle.setText("Resultado de Ataque");
        resultPanel.add(resultadoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        AtkResulttx.setBackground(new java.awt.Color(0, 153, 204));
        AtkResulttx.setColumns(20);
        AtkResulttx.setRows(5);
        AtkResulttx.setFocusable(false);
        jScrollPane3.setViewportView(AtkResulttx);

        resultPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 340, 80));

        mainPanel.add(resultPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 130));

        luchadoresPanel.setBackground(new java.awt.Color(0, 153, 204));
        luchadoresPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        luchadoresPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageluchador1.setBackground(new java.awt.Color(6, 112, 187));
        imageluchador1.setOpaque(true);
        luchadoresPanel.add(imageluchador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 190));

        imageluchador3.setBackground(new java.awt.Color(64, 64, 64));
        imageluchador3.setOpaque(true);
        luchadoresPanel.add(imageluchador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 150, 190));

        imageluchador2.setBackground(new java.awt.Color(197, 81, 80));
        imageluchador2.setOpaque(true);
        luchadoresPanel.add(imageluchador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 150, 190));

        luchador2Panel1.setOpaque(false);
        luchador2Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        porcentajeluchador3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        porcentajeluchador3.setForeground(new java.awt.Color(240, 240, 240));
        porcentajeluchador3.setText("xx%");
        luchador2Panel1.add(porcentajeluchador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, -1));

        nombre3.setBackground(new java.awt.Color(255, 51, 0));
        nombre3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre3.setForeground(new java.awt.Color(255, 51, 0));
        nombre3.setText("nombre1");
        nombre3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel1.add(nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        tipo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipo3.setForeground(new java.awt.Color(255, 153, 102));
        tipo3.setText("nombre1");
        tipo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel1.add(tipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        poder1Title2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        poder1Title2.setForeground(new java.awt.Color(240, 240, 240));
        poder1Title2.setText("Poder");
        poder1Title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel1.add(poder1Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        poder3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        poder3.setForeground(new java.awt.Color(240, 240, 240));
        poder3.setText("Poder");
        poder3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel1.add(poder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        resistencia1Title2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resistencia1Title2.setForeground(new java.awt.Color(240, 240, 240));
        resistencia1Title2.setText("Resistencia");
        resistencia1Title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel1.add(resistencia1Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        resistencia3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resistencia3.setForeground(new java.awt.Color(240, 240, 240));
        resistencia3.setText("Resistencia");
        resistencia3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel1.add(resistencia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        sanidad1Title2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sanidad1Title2.setForeground(new java.awt.Color(240, 240, 240));
        sanidad1Title2.setText("Sanidad");
        sanidad1Title2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel1.add(sanidad1Title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        sanidad3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sanidad3.setForeground(new java.awt.Color(240, 240, 240));
        sanidad3.setText("Sanidad");
        sanidad3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel1.add(sanidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        luchadoresPanel.add(luchador2Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 180, 190));

        luchador2Panel.setOpaque(false);
        luchador2Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        porcentajeluchador2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        porcentajeluchador2.setForeground(new java.awt.Color(240, 240, 240));
        porcentajeluchador2.setText("xx%");
        luchador2Panel.add(porcentajeluchador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, -1));

        nombre2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre2.setForeground(new java.awt.Color(255, 51, 0));
        nombre2.setText("nombre1");
        nombre2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel.add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        tipo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipo2.setForeground(new java.awt.Color(255, 153, 102));
        tipo2.setText("nombre1");
        tipo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel.add(tipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        poder1Title1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        poder1Title1.setForeground(new java.awt.Color(240, 240, 240));
        poder1Title1.setText("Poder");
        poder1Title1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel.add(poder1Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        poder2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        poder2.setForeground(new java.awt.Color(240, 240, 240));
        poder2.setText("Poder");
        poder2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel.add(poder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        resistencia1Title1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resistencia1Title1.setForeground(new java.awt.Color(240, 240, 240));
        resistencia1Title1.setText("Resistencia");
        resistencia1Title1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel.add(resistencia1Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        resistencia2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resistencia2.setForeground(new java.awt.Color(240, 240, 240));
        resistencia2.setText("Resistencia");
        resistencia2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel.add(resistencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        sanidad1Title1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sanidad1Title1.setForeground(new java.awt.Color(240, 240, 240));
        sanidad1Title1.setText("Sanidad");
        sanidad1Title1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel.add(sanidad1Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        sanidad2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sanidad2.setForeground(new java.awt.Color(240, 240, 240));
        sanidad2.setText("Sanidad");
        sanidad2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador2Panel.add(sanidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        luchadoresPanel.add(luchador2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 180, 190));

        luchador1Panel.setForeground(new java.awt.Color(255, 153, 102));
        luchador1Panel.setOpaque(false);
        luchador1Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        porcentajeluchador1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        porcentajeluchador1.setForeground(new java.awt.Color(240, 240, 240));
        porcentajeluchador1.setText("xx%");
        luchador1Panel.add(porcentajeluchador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, -1));

        nombre1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre1.setForeground(new java.awt.Color(255, 51, 0));
        nombre1.setText("nombre1");
        nombre1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador1Panel.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        tipo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipo1.setForeground(new java.awt.Color(255, 153, 102));
        tipo1.setText("nombre1");
        tipo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador1Panel.add(tipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        poder1Title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        poder1Title.setForeground(new java.awt.Color(240, 240, 240));
        poder1Title.setText("Poder");
        poder1Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador1Panel.add(poder1Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        poder1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        poder1.setForeground(new java.awt.Color(240, 240, 240));
        poder1.setText("Poder");
        poder1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador1Panel.add(poder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        resistencia1Title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resistencia1Title.setForeground(new java.awt.Color(240, 240, 240));
        resistencia1Title.setText("Resistencia");
        resistencia1Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador1Panel.add(resistencia1Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        resistencia1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resistencia1.setForeground(new java.awt.Color(240, 240, 240));
        resistencia1.setText("Resistencia");
        resistencia1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador1Panel.add(resistencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        sanidad1Title.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sanidad1Title.setForeground(new java.awt.Color(240, 240, 240));
        sanidad1Title.setText("Sanidad");
        sanidad1Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador1Panel.add(sanidad1Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        sanidad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sanidad1.setForeground(new java.awt.Color(240, 240, 240));
        sanidad1.setText("Sanidad");
        sanidad1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        luchador1Panel.add(sanidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        luchadoresPanel.add(luchador1Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 180, 190));

        mainPanel.add(luchadoresPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 370, 680));

        bitacoraPanel.setBackground(new java.awt.Color(43, 65, 235,100));
        bitacoraPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        bitacoraPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bitacoraTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bitacoraTitle.setForeground(new java.awt.Color(240, 240, 240));
        bitacoraTitle.setText("Bitácora");
        bitacoraPanel.add(bitacoraTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        jScrollPane1.setOpaque(false);

        bitacoraTx.setBackground(new java.awt.Color(0, 153, 204));
        bitacoraTx.setColumns(20);
        bitacoraTx.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        bitacoraTx.setForeground(new java.awt.Color(255, 255, 255));
        bitacoraTx.setRows(5);
        bitacoraTx.setFocusable(false);
        jScrollPane1.setViewportView(bitacoraTx);

        bitacoraPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 340, 480));

        mainPanel.add(bitacoraPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 360, 540));

        cmdPanel.setBackground(new java.awt.Color(43, 65, 235,100));
        cmdPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        cmdPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);

        consolaTx.setBackground(new java.awt.Color(0, 153, 204));
        consolaTx.setColumns(20);
        consolaTx.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        consolaTx.setRows(5);
        consolaTx.setBorder(null);
        consolaTx.setFocusable(false);
        jScrollPane2.setViewportView(consolaTx);

        cmdPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1500, 140));

        inputTf.setBackground(new java.awt.Color(0, 51, 153));
        inputTf.setForeground(new java.awt.Color(255, 255, 255));
        inputTf.setBorder(null);
        inputTf.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        inputTf.setDoubleBuffered(true);
        inputTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputTfKeyPressed(evt);
            }
        });
        cmdPanel.add(inputTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 1360, 20));

        mainPanel.add(cmdPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 1520, 190));

        tableroPanel.setBackground(new java.awt.Color(43, 65, 235,100));
        tableroPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        tableroPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        matrizPanel.setLayout(new java.awt.GridLayout(20, 30));
        tableroPanel.add(matrizPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 760, 510));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        proporcion3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel1.add(proporcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 114, 24));

        nombrePorcentaje3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(nombrePorcentaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 69, 24));

        nombreP3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(nombreP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 69, 24));

        proporcion2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel1.add(proporcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 114, 24));

        nombrePorcentaje2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(nombrePorcentaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 69, 24));

        nombreP2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(nombreP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 69, 24));

        nombrePorcentaje1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(nombrePorcentaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 53, 69, 24));

        nombreP1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(nombreP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 23, 69, 24));

        proporcion1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel1.add(proporcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 114, 24));

        tableroPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 750, 130));

        mainPanel.add(tableroPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 770, 680));

        oceanoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.png"))); // NOI18N
        mainPanel.add(oceanoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTfKeyPressed
        String tx = this.inputTf.getText();
        if (evt.getKeyCode()== VK_ENTER && tx.trim().length() != 0){
            this.addMensaje(tx);
            this.inputTf.setText("");
            CommandMain.startCommand(tx);
        }
    }//GEN-LAST:event_inputTfKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AtkResulttx;
    private javax.swing.JPanel bitacoraPanel;
    private javax.swing.JLabel bitacoraTitle;
    private javax.swing.JTextArea bitacoraTx;
    private javax.swing.JPanel cmdPanel;
    private javax.swing.JTextArea consolaTx;
    private javax.swing.JLabel imageluchador1;
    private javax.swing.JLabel imageluchador2;
    private javax.swing.JLabel imageluchador3;
    private javax.swing.JTextField inputTf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel luchador1Panel;
    private javax.swing.JPanel luchador2Panel;
    private javax.swing.JPanel luchador2Panel1;
    private javax.swing.JPanel luchadoresPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel matrizPanel;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JLabel nombre3;
    private javax.swing.JLabel nombreP1;
    private javax.swing.JLabel nombreP2;
    private javax.swing.JLabel nombreP3;
    private javax.swing.JLabel nombrePorcentaje1;
    private javax.swing.JLabel nombrePorcentaje2;
    private javax.swing.JLabel nombrePorcentaje3;
    private javax.swing.JLabel oceanoLabel;
    private javax.swing.JLabel poder1;
    private javax.swing.JLabel poder1Title;
    private javax.swing.JLabel poder1Title1;
    private javax.swing.JLabel poder1Title2;
    private javax.swing.JLabel poder2;
    private javax.swing.JLabel poder3;
    private javax.swing.JLabel porcentajeluchador1;
    private javax.swing.JLabel porcentajeluchador2;
    private javax.swing.JLabel porcentajeluchador3;
    private javax.swing.JLabel proporcion1;
    private javax.swing.JLabel proporcion2;
    private javax.swing.JLabel proporcion3;
    private javax.swing.JLabel resistencia1;
    private javax.swing.JLabel resistencia1Title;
    private javax.swing.JLabel resistencia1Title1;
    private javax.swing.JLabel resistencia1Title2;
    private javax.swing.JLabel resistencia2;
    private javax.swing.JLabel resistencia3;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JLabel resultadoTitle;
    private javax.swing.JLabel sanidad1;
    private javax.swing.JLabel sanidad1Title;
    private javax.swing.JLabel sanidad1Title1;
    private javax.swing.JLabel sanidad1Title2;
    private javax.swing.JLabel sanidad2;
    private javax.swing.JLabel sanidad3;
    private javax.swing.JPanel tableroPanel;
    private javax.swing.JLabel tipo1;
    private javax.swing.JLabel tipo2;
    private javax.swing.JLabel tipo3;
    // End of variables declaration//GEN-END:variables

    void setNombreTurno(String nombreTurno) {
        this.nombreTurno = nombreTurno;
        this.addMensajeBitacora("Turno de: "+nombreTurno);
    }

    public void addMensaje(String mensaje) {
        this.consolaTx.append(mensaje + "\n");
    }
    
    public void addMensajeResult(String mensaje) {
        this.AtkResulttx.append(mensaje + "\n");
    }
    
    public void addMensajeBitacora(String mensaje) {
        this.bitacoraTx.append(mensaje + "\n");
    }

    void setInicioPartida(int op) {
        if(op == 1){
            this.addMensajeBitacora("Partida Iniciada");
            this.iniciada = true;
            this.drawPopulation();
        }
        else{
            this.addMensajeBitacora("Aun no se puede iniciar");
        }
    }

    void setIndexFi(int idx) {
        this.indexFi = idx;
    }
    
    public void vidaCasillas(){
        this.juego.vidaCasillas();
    }

    public void limpiarVidaCasillas() {
        this.juego.limpiarVidaCasillas();
    }
    public void updatePorcentajes() {
        int cont =0;
        for(int i=0; i<this.juego.unidades.size();i++){
            for(int j=0; j<this.juego.unidades.get(i).poblacionLuchador.size(); j++){
                if(this.juego.unidades.get(i).poblacionLuchador.get(j).vivo){
                    cont++;
                }
            }
            switch(i){
                case 0:
                    this.proporcion1.setText(cont + " de "+((this.juego.unidades.get(i).getPercentage()*600)/100)+" casillas");
                    this.nombreP1.setText(this.juego.unidades.get(i).getName());
                    this.nombrePorcentaje1.setText(((cont*100)/((this.juego.unidades.get(i).getPercentage()*600)/100))+"%");
                    break;
                case 1:
                    this.proporcion2.setText(cont + " de "+((this.juego.unidades.get(i).getPercentage()*600)/100)+" casillas");
                    this.nombreP2.setText(this.juego.unidades.get(i).getName());
                    this.nombrePorcentaje2.setText(((cont*100)/((this.juego.unidades.get(i).getPercentage()*600)/100))+"%");
                    break;
                case 2:
                    this.proporcion3.setText(cont + " de "+((this.juego.unidades.get(i).getPercentage()*600)/100)+" casillas");
                    this.nombreP3.setText(this.juego.unidades.get(i).getName());
                    this.nombrePorcentaje3.setText(((cont*100)/((this.juego.unidades.get(i).getPercentage()*600)/100))+"%");
                    break;
            }
            cont=0;
        }
    }

    public void consultCasilla(Integer x, Integer y) {
        this.addMensajeBitacora(this.juego.consultCasilla(x, y));
    }
    
    public String consultPlayer() {
        return juego.getInfo();
    }

    void setJugadores(int idx, String name) {
        if(name.equals(this.getTitle())){
            this.indexFi = idx;
        }
        this.juego.addPlayer(name, idx);
    }
    void drawPopulation() {
        for(int i =0; i<20;i++){
                    for(int j =0; j<30;j++){
                        
                        this.matrizPanel.add(juego.poblacion[i][j].refLabel);
                        
                        
  
                    }
        }
         this.setVisible(true); 
         this.updatePorcentajes();
    }
    public boolean addFighter(String Name, Integer percentage, Tipo grupo,Integer poder,Integer resistencia,Integer autosanidad, String Imagen) {
        
        if(((poder == 50)  || (poder == 75) || (poder==100)) && ((resistencia == 50)  || (resistencia == 75) || (resistencia==100)) && ((autosanidad == 50)  || (autosanidad == 75) || (autosanidad==100)) && percentage > 0 && juego.unidades.size() < 3){
            boolean valido=true;
            int percentage1 = 0;
            int percentage2 = 0;
            for(int i =0; i<juego.unidades.size(); i++){
                if(juego.unidades.get(i).getPower() == poder || juego.unidades.get(i).getResistance()== resistencia || juego.unidades.get(i).getSanity() ==autosanidad || juego.unidades.get(i).getName().equals(Name)){
                    valido=false;
                    break;
                }
                if(percentage1 == 0){
                    percentage1 = juego.unidades.get(i).getPercentage();
                }
                else if(percentage2 == 0){
                    percentage2 = juego.unidades.get(i).getPercentage();
                }
            }
            if(percentage2+percentage1+percentage > 100){
                valido=false;
            }
            else if(percentage2+percentage1+percentage == 100 && juego.unidades.size() < 2){
                valido=false;
            }
            else if(percentage2+percentage1+percentage < 100 && juego.unidades.size() == 2){
                valido=false;
            }
            else if(percentage2 == 0 && percentage1 == 0 && percentage == 99){
                valido=false;
            }
            if(valido){
                switch(juego.unidades.size()){
                    case 0:
                        juego.unidades.add(new Luchador(Name,percentage,grupo,autosanidad,poder, resistencia ));
                        this.imageluchador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Luchadores/"+Imagen)));
                        this.nombre1.setText(Name);
                        this.tipo1.setText(grupo.getNombre());
                        this.sanidad1.setText(""+autosanidad);
                        this.resistencia1.setText(""+resistencia);
                        this.poder1.setText(""+poder);
                        this.porcentajeluchador1.setText(""+percentage+"%");
                        
                        break;
                    case 1:
                        juego.unidades.add(new Luchador(Name,percentage,grupo, autosanidad,poder, resistencia ));
                        this.imageluchador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Luchadores/"+Imagen)));
                        this.nombre2.setText(Name);
                        this.tipo2.setText(grupo.getNombre());
                        this.sanidad2.setText(""+autosanidad);
                        this.resistencia2.setText(""+resistencia);
                        this.poder2.setText(""+poder);
                        this.porcentajeluchador2.setText(""+percentage+"%");
                        break;
                    case 2:
                        juego.unidades.add(new Luchador(Name,percentage,grupo, autosanidad,poder, resistencia ));
                        this.imageluchador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Luchadores/"+Imagen)));
                        this.nombre3.setText(Name);
                        this.tipo3.setText(grupo.getNombre());
                        this.sanidad3.setText(""+autosanidad);
                        this.resistencia3.setText(""+resistencia);
                        this.poder3.setText(""+poder);
                        this.porcentajeluchador3.setText(""+percentage+"%");
                        break;
                    
                }
                javax.swing.JLabel temp;
                ArrayList<Point>casillasVacias= new ArrayList<Point>();
                for(int i =0; i<20;i++){
                    for(int j =0; j<30;j++){
                        if(juego.poblacion[i][j]==null){
                            casillasVacias.add(new Point(i,j));
                        }
                        
        //                System.out.println("["+i+"]"+"["+j+"]");
                    }
                }
                int newPoblacion = (600*percentage)/100;
                int randomPlacement;
                Point punto;
                while(newPoblacion!=0){
                     randomPlacement = (new Random()).nextInt(casillasVacias.size());
                    punto = casillasVacias.get(randomPlacement);
                    casillasVacias.remove(randomPlacement);
                    
                    temp = new javax.swing.JLabel("",javax.swing.SwingConstants.CENTER);
                    temp.setPreferredSize(new java.awt.Dimension(20, 20));
                    temp.setAlignmentY(0.0F);
                    temp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
                    temp.setOpaque(true);
                    temp.setForeground(new java.awt.Color(255, 255, 255));
    //              temp.setBackground(new java.awt.Color(114, 47, 55));
                    int color = (new Random()).nextInt(3);
                    switch(juego.unidades.size()){
                        case 1:
                            temp.setBackground(new java.awt.Color(6, 112, 187));
                            break;
                        case 2:
                            temp.setBackground(new java.awt.Color(197, 81, 40));
                            break;
                        case 3:
                            temp.setBackground(new java.awt.Color(64, 64, 64));
                            break;
                    }
                    //matrizPanel.add(temp);
                    Casilla newCasilla = new Casilla(temp, 100, resistencia);
                    this.juego.addPoblacion(newCasilla, punto.x, punto.y);
                    this.juego.unidades.get(juego.unidades.size()-1).addPoblacion(newCasilla);
                    newPoblacion--;
                }
                return true;
            }else{
                return false;
            }
        }
        return false;
    }

    void setNombreGanador(String nombreGanador) {
        this.nombreTurno = "";
        this.addMensajeBitacora(nombreGanador+" ha sido nuestro ganador!!");
    }

    
}
